"""

Revision ID: 4c7820d3ea3c
Revises: c9392eaa3cb0
Create Date: 2026-04-28 15:24:46.948352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7820d3ea3c'
down_revision: Union[str, Sequence[str], None] = 'c9392eaa3cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'last_message_id')
    # ### end Alembic commands ###
